server:
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
  port: 8123

spring:
  # 空间图片分表
  shardingsphere:
    datasource:
      names: yu_picture
      yu_picture:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/yu_picture
        username: root
        password: 020325ggg
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: yu_picture.picture  # 动态分表
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              # 确保这个路径和你项目中 PictureShardingAlgorithm.java 文件的实际包路径一致
              algorithmClassName: com.yunpicture.yunpicturebackend.manage.sharding.PictureShardingAlgorithm
    props:
      sql-show: true
  application:
    name: yu-picture-backend
  servlet:
    multipart:
      max-file-size: 10MB
  #    数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_picture
    username: root
    password: 020325ggg
#    redis 配置
  redis:
    database: 2
    host: 192.168.100.128
    port: 6379
    timeout: 5000
    password: 020325ggg
  session:
    store-type: redis
    timeout: 2592000
  #    session 30天时间
  profiles:
    active: local
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    enable-sql-runner: true
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

#接口文档配置
knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yunpicture.yunpicturebackend.controller
          -
#
#cos:
#  client:
#    host:
#    secretId:
#    secretKey:
#    region:
#    bucket:


